name: CI/CD Control de Gastos

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-22.04  # <--- Etiqueta específica más común en Gitea
    steps:
      - name: Checkout Código
        uses: https://github.com/actions/checkout@v4 # <--- URL completa

      - name: Iniciar sesión en Gitea Registry
        uses: https://github.com/docker/login-action@v3 # <--- URL completa
        with:
          registry: gitea.servespinoza.xyz
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build y Push de Backend
        run: |
          docker build \
            --tag gitea.servespinoza.xyz/luismario/controlgastos-backend:latest \
            ./backend
          docker push gitea.servespinoza.xyz/luismario/controlgastos-backend:latest

      - name: Build y Push de Frontend
        run: |
          docker build \
            --tag gitea.servespinoza.xyz/luismario/controlgastos-frontend:latest \
            --build-arg VITE_API_URL=http://192.168.0.97:3000 \
            ./frontend
          docker push gitea.servespinoza.xyz/luismario/controlgastos-frontend:latest
